spring:
  application:
    name: markdown-reviewer
  ai:
    openai:
      api-key: --PREENCHER
      chat:
        options:
          model: gpt-4.1-nano-2025-04-14
  shell:
    interactive:
      enabled: true
